'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ModuleService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="mod_type", [Namespace]:="http://tempuri.org/")>  _
    Public Enum mod_type As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        D = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        T = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        R = 2
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Modulex", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Modulex
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private versionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private display_nameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private file_assemblyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private namespceField As String
        
        Private typeField As ModuleService.mod_type
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private fileField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property version() As String
            Get
                Return Me.versionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.versionField, value) <> true) Then
                    Me.versionField = value
                    Me.RaisePropertyChanged("version")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property display_name() As String
            Get
                Return Me.display_nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.display_nameField, value) <> true) Then
                    Me.display_nameField = value
                    Me.RaisePropertyChanged("display_name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property file_assembly() As String
            Get
                Return Me.file_assemblyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.file_assemblyField, value) <> true) Then
                    Me.file_assemblyField = value
                    Me.RaisePropertyChanged("file_assembly")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property namespce() As String
            Get
                Return Me.namespceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.namespceField, value) <> true) Then
                    Me.namespceField = value
                    Me.RaisePropertyChanged("namespce")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property type() As ModuleService.mod_type
            Get
                Return Me.typeField
            End Get
            Set
                If (Me.typeField.Equals(value) <> true) Then
                    Me.typeField = value
                    Me.RaisePropertyChanged("type")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property file() As String
            Get
                Return Me.fileField
            End Get
            Set
                If (Object.ReferenceEquals(Me.fileField, value) <> true) Then
                    Me.fileField = value
                    Me.RaisePropertyChanged("file")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ModuleService.VersionsSoap")>  _
    Public Interface VersionsSoap
        
        'CODEGEN: Generating message contract since element name Get_Type_NameResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Get_Type_Name", ReplyAction:="*")>  _
        Function Get_Type_Name(ByVal request As ModuleService.Get_Type_NameRequest) As ModuleService.Get_Type_NameResponse
        
        'CODEGEN: Generating message contract since element name type from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Get_Single_Char_Identifer", ReplyAction:="*")>  _
        Function Get_Single_Char_Identifer(ByVal request As ModuleService.Get_Single_Char_IdentiferRequest) As ModuleService.Get_Single_Char_IdentiferResponse
        
        'CODEGEN: Generating message contract since element name Get_ModulesResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Get_Modules", ReplyAction:="*")>  _
        Function Get_Modules(ByVal request As ModuleService.Get_ModulesRequest) As ModuleService.Get_ModulesResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Get_Type_NameRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Get_Type_Name", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ModuleService.Get_Type_NameRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ModuleService.Get_Type_NameRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Get_Type_NameRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public typex As ModuleService.mod_type
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal typex As ModuleService.mod_type)
            MyBase.New
            Me.typex = typex
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Get_Type_NameResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Get_Type_NameResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ModuleService.Get_Type_NameResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ModuleService.Get_Type_NameResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Get_Type_NameResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Get_Type_NameResult As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public typex As ModuleService.mod_type
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Get_Type_NameResult As String, ByVal typex As ModuleService.mod_type)
            MyBase.New
            Me.Get_Type_NameResult = Get_Type_NameResult
            Me.typex = typex
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Get_Single_Char_IdentiferRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Get_Single_Char_Identifer", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ModuleService.Get_Single_Char_IdentiferRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ModuleService.Get_Single_Char_IdentiferRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Get_Single_Char_IdentiferRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public type As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal type As String)
            MyBase.New
            Me.type = type
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Get_Single_Char_IdentiferResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Get_Single_Char_IdentiferResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ModuleService.Get_Single_Char_IdentiferResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ModuleService.Get_Single_Char_IdentiferResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Get_Single_Char_IdentiferResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Get_Single_Char_IdentiferResult As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public type As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Get_Single_Char_IdentiferResult As String, ByVal type As String)
            MyBase.New
            Me.Get_Single_Char_IdentiferResult = Get_Single_Char_IdentiferResult
            Me.type = type
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Get_ModulesRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Get_Modules", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ModuleService.Get_ModulesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ModuleService.Get_ModulesRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class Get_ModulesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Get_ModulesResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Get_ModulesResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ModuleService.Get_ModulesResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ModuleService.Get_ModulesResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Get_ModulesResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Get_ModulesResult As System.Collections.Generic.List(Of ModuleService.Modulex)
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Get_ModulesResult As System.Collections.Generic.List(Of ModuleService.Modulex))
            MyBase.New
            Me.Get_ModulesResult = Get_ModulesResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface VersionsSoapChannel
        Inherits ModuleService.VersionsSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class VersionsSoapClient
        Inherits System.ServiceModel.ClientBase(Of ModuleService.VersionsSoap)
        Implements ModuleService.VersionsSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ModuleService_VersionsSoap_Get_Type_Name(ByVal request As ModuleService.Get_Type_NameRequest) As ModuleService.Get_Type_NameResponse Implements ModuleService.VersionsSoap.Get_Type_Name
            Return MyBase.Channel.Get_Type_Name(request)
        End Function
        
        Public Function Get_Type_Name(ByRef typex As ModuleService.mod_type) As String
            Dim inValue As ModuleService.Get_Type_NameRequest = New ModuleService.Get_Type_NameRequest()
            inValue.Body = New ModuleService.Get_Type_NameRequestBody()
            inValue.Body.typex = typex
            Dim retVal As ModuleService.Get_Type_NameResponse = CType(Me,ModuleService.VersionsSoap).Get_Type_Name(inValue)
            typex = retVal.Body.typex
            Return retVal.Body.Get_Type_NameResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ModuleService_VersionsSoap_Get_Single_Char_Identifer(ByVal request As ModuleService.Get_Single_Char_IdentiferRequest) As ModuleService.Get_Single_Char_IdentiferResponse Implements ModuleService.VersionsSoap.Get_Single_Char_Identifer
            Return MyBase.Channel.Get_Single_Char_Identifer(request)
        End Function
        
        Public Function Get_Single_Char_Identifer(ByRef type As String) As String
            Dim inValue As ModuleService.Get_Single_Char_IdentiferRequest = New ModuleService.Get_Single_Char_IdentiferRequest()
            inValue.Body = New ModuleService.Get_Single_Char_IdentiferRequestBody()
            inValue.Body.type = type
            Dim retVal As ModuleService.Get_Single_Char_IdentiferResponse = CType(Me,ModuleService.VersionsSoap).Get_Single_Char_Identifer(inValue)
            type = retVal.Body.type
            Return retVal.Body.Get_Single_Char_IdentiferResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ModuleService_VersionsSoap_Get_Modules(ByVal request As ModuleService.Get_ModulesRequest) As ModuleService.Get_ModulesResponse Implements ModuleService.VersionsSoap.Get_Modules
            Return MyBase.Channel.Get_Modules(request)
        End Function
        
        Public Function Get_Modules() As System.Collections.Generic.List(Of ModuleService.Modulex)
            Dim inValue As ModuleService.Get_ModulesRequest = New ModuleService.Get_ModulesRequest()
            inValue.Body = New ModuleService.Get_ModulesRequestBody()
            Dim retVal As ModuleService.Get_ModulesResponse = CType(Me,ModuleService.VersionsSoap).Get_Modules(inValue)
            Return retVal.Body.Get_ModulesResult
        End Function
    End Class
End Namespace
