Public Class APT1

    Public Function Process(ByRef line As String) As Entity.APT
        Dim apt As New Entity.APT

        With apt
            .site_code = GetPart(line, 4, 11)
            .type = GetPart(line, 15, 13)
            .icao = GetPart(line, 28, 4)
            .effective = GetPart(line, 32, 10)
            .region_code = GetPart(line, 42, 3)
            .fsdo = GetPart(line, 45, 4)
            .state_code = GetPart(line, 49, 2)
            .state = GetPart(line, 51, 20)
            .county = GetPart(line, 71, 21)
            .county_state_code = GetPart(line, 92, 2)
            .city = GetPart(line, 94, 40)
            .airport_name = GetPart(line, 134, 50)
            .owner_type = GetPart(line, 184, 2)
            .airport_use_type = GetPart(line, 186, 2)
            .owner_name = GetPart(line, 188, 35)
            .owner_address = GetPart(line, 223, 72)
            .owner_address_line2 = GetPart(line, 295, 45)
            .owner_phone = GetPart(line, 340, 16)
            .manager_name = GetPart(line, 356, 35)
            .manager_address = GetPart(line, 391, 72)
            .manager_address_line2 = GetPart(line, 463, 45)
            .manager_phone = GetPart(line, 508, 16)
            .latitude = LatLong_To_Degrees(GetPart(line, 524, 15))
            .latitude_seconds = GetPart(line, 539, 12)
            .longitude = LatLong_To_Degrees(GetPart(line, 551, 15))
            .longitude_seconds = GetPart(line, 566, 12)
            .geo_determination = GetPart(line, 578, 1)
            .elevation_msl = GetPart(line, 579, 7)
            .elevation_determination = GetPart(line, 586, 1)
            .magnetic_variation = GetPart(line, 587, 3)
            .magnetic_variation_epoch = GetPart(line, 590, 4)
            .tpa_agl = GetPart(line, 594, 4)
            .sectional = GetPart(line, 598, 30)
            .distance_from_town = GetPart(line, 628, 2)
            .distance_direction = GetPart(line, 630, 3)
            .acres = GetPart(line, 633, 5)
            .artcc_ident = GetPart(line, 638, 4)
            .artcc_computer_ident = GetPart(line, 642, 3)
            .artcc_name = GetPart(line, 645, 30)
            .artcc_responsible_ident = GetPart(line, 675, 4)
            .artcc_responsible_computer_ident = GetPart(line, 679, 3)
            .artcc_responsible_name = GetPart(line, 682, 30)
            .fss_tiein_available = GetPart(line, 712, 1)
            .fss_tiein_ident = GetPart(line, 713, 4)
            .fss_tiein_name = GetPart(line, 717, 30)
            .fss_phone = GetPart(line, 747, 16)
            .fss_phone_free = GetPart(line, 763, 16)
            .fss_alternate_ident = GetPart(line, 779, 4)
            .fss_alternate_name = GetPart(line, 783, 30)
            .fss_alternate_phone_free = GetPart(line, 813, 16)
            .fss_notam_ident = GetPart(line, 829, 4)
            .notam_d_available = GetPart(line, 833, 1)
            .activation_date = GetPart(line, 834, 7)
            .airport_status = GetPart(line, 841, 2)
            .airport_arff_type = GetPart(line, 843, 15)
            .npias_code = GetPart(line, 858, 7)
            .airspace_analysis = GetPart(line, 865, 13)
            .AOE = GetPart(line, 878, 1)
            .Landing_Rights = GetPart(line, 879, 1)
            .mil_civil_agreement = GetPart(line, 880, 1)
            .mil_landing_rights = GetPart(line, 881, 1)
            .inspection_method = GetPart(line, 882, 2)
            .inspection_group = GetPart(line, 884, 1)
            .last_inspection = GetPart(line, 885, 8)
            .last_inspection_request = GetPart(line, 893, 8)
            .fuel = GetPart(line, 901, 40)
            .airframe_repair_service = GetPart(line, 941, 5)
            .powerplant_repair_service = GetPart(line, 946, 5)
            .oxygen_bottle_service = GetPart(line, 951, 8)
            .oxygen_bulk_service = GetPart(line, 959, 8)
            .light_schedule = GetPart(line, 967, 7)
            .beacon_schedule = GetPart(line, 974, 7)
            .has_tower = GetPart(line, 981, 1)
            .radio_unicom = GetPart(line, 982, 7)
            .radio_common = GetPart(line, 989, 7)
            .segmented_circle = GetPart(line, 996, 4)
            .beacon_color = GetPart(line, 1000, 3)
            .non_commericial_landing_fee = GetPart(line, 1003, 1)
            .medical_use = GetPart(line, 1004, 1)
            .single_engine_GA_based = GetPart(line, 1005, 3)
            .multi_engine_GA_based = GetPart(line, 1008, 3)
            .jet_engine_based = GetPart(line, 1011, 3)
            .helicopter_GA_based = GetPart(line, 1014, 3)
            .gliders_based = GetPart(line, 1017, 3)
            .military_based = GetPart(line, 1020, 3)
            .ultralight_based = GetPart(line, 1023, 3)
            .commerical_services = GetPart(line, 1026, 6)
            .commuter_services = GetPart(line, 1032, 6)
            .air_taxi = GetPart(line, 1038, 6)
            .GA_local = GetPart(line, 1044, 6)
            .GA_itinerant = GetPart(line, 1050, 6)
            .military_ops = GetPart(line, 1056, 6)
            .annual_ops = GetPart(line, 1062, 10)
            .position_source = GetPart(line, 1072, 16)
            .position_source_date = GetPart(line, 1088, 10)
            .elevation_source = GetPart(line, 1098, 16)
            .elevation_source_date = GetPart(line, 1114, 10)
            .contract_fuel = GetPart(line, 1124, 1)
            .storage_available = GetPart(line, 1125, 12)
            .available_services = GetPart(line, 1137, 71)
            .wind_indicator = GetPart(line, 1208, 3)
            .icao_ident = GetPart(line, 1211, 7)
        End With

        Return apt
    End Function

End Class
