Public Class NAV1

    Public Function Process(ByRef line As String) As Entity.NAV1
        Dim nav As New Entity.NAV1

        With nav
            .icao = GetPart(line, 5, 4)
            .type = GetPart(line, 9, 20)
            .official_icao = GetPart(line, 29, 4)
            .effective = GetPart(line, 33, 10)
            .navaid_name = GetPart(line, 43, 30)
            .city = GetPart(line, 73, 40)
            .state = GetPart(line, 113, 30)
            .state_code = GetPart(line, 143, 2)
            .region_code = GetPart(line, 145, 3)
            .country = GetPart(line, 148, 30)
            .country_state_code = GetPart(line, 178, 2)
            .owner_name = GetPart(line, 180, 50)
            .operator_name = GetPart(line, 230, 50)
            .common_use = GetPart(line, 280, 1)
            .public_use = GetPart(line, 281, 1)
            .[class] = GetPart(line, 282, 11)
            .hours = GetPart(line, 293, 11)
            .artcc_high = GetPart(line, 304, 4)
            .artcc_high_name = GetPart(line, 308, 30)
            .artcc_low = GetPart(line, 338, 4)
            .artcc_low_name = GetPart(line, 342, 30)
            .latitude = LatLong_To_Degrees(GetPart(line, 372, 14))
            .latitude_seconds = GetPart(line, 386, 11)
            .longitude = LatLong_To_Degrees(GetPart(line, 397, 14))
            .longitude_seconds = GetPart(line, 411, 11)
            .tacan_latitude = LatLong_To_Degrees(GetPart(line, 423, 14))
            .tacan_latitude_seconds = GetPart(line, 437, 11)
            .tacan_longitude = LatLong_To_Degrees(GetPart(line, 448, 14))
            .tacan_longitude_seconds = GetPart(line, 462, 11)
            .elevation_msl = GetPart(line, 473, 7)
            .magnetic_variation = GetPart(line, 480, 5)
            .magnetic_variation_epoch = GetPart(line, 485, 4)
            .voice_feature = GetPart(line, 489, 3)
            .power_output_watts = GetPart(line, 492, 4)
            .voice_identification = GetPart(line, 496, 3)
            .monitor_category = GetPart(line, 499, 1)
            .radio_name = GetPart(line, 500, 30)
            .tacan_channel = GetPart(line, 530, 4)
            .radio = GetPart(line, 534, 6)
            .fan_marker = GetPart(line, 540, 24)
            .fan_marker_type = GetPart(line, 564, 10)
            .fan_true_bearing = GetPart(line, 574, 3)
            .tacan_type = GetPart(line, 577, 1)
            .low_altitude_used = GetPart(line, 578, 3)
            .z_marker_available = GetPart(line, 581, 3)
            .TWEB_hours = GetPart(line, 584, 9)
            .TWEB_phone = GetPart(line, 593, 20)
            .FSS = GetPart(line, 613, 4)
            .FSS_Name = GetPart(line, 617, 30)
            .FSS_hours = GetPart(line, 647, 100)
            .NOTAM_ident = GetPart(line, 747, 4)
            .quadrant_ident = GetPart(line, 751, 16)
            .status = GetPart(line, 767, 30)
            .pitch = GetPart(line, 797, 1)
            .[catch] = GetPart(line, 798, 1)
            .sua_atcaa = GetPart(line, 799, 1)
            .restriction_flag = GetPart(line, 800, 1)
            .hiwas_flag = GetPart(line, 801, 1)
            .tweb_restriction = GetPart(line, 802, 1)
        End With

        Return nav
    End Function

End Class
