//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERMService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY
    {
        public string COMPANY_CODE { get; set; }
        public string COMPANY_NM { get; set; }
        public string DISTRIBUTION_TYPE_CODE { get; set; }
        public string OLD_COMPANY_CODE { get; set; }
        public string ACCT_ADMIN_CODE { get; set; }
    }
}
