//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERMService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERM_FINANCIAL_VALUE
    {
        public int ERM_RUN_ID { get; set; }
        public int ERM_RUN_VERSION_ID { get; set; }
        public int ERM_SHOCK_GROUP_SEQ_ID { get; set; }
        public Nullable<int> ERM_PERIOD_TYPE_SEQ_ID { get; set; }
        public int ERM_PERIOD_ID { get; set; }
        public Nullable<int> ERM_FINANCIAL_COLUMN_SEQ_ID { get; set; }
        public Nullable<decimal> ERM_FINANCIAL_COLUMN_VALUE { get; set; }
        public System.DateTime INSERT_DT { get; set; }
    
        public virtual ERM_FINANCIAL_COLUMN ERM_FINANCIAL_COLUMN { get; set; }
        public virtual ERM_PERIOD_TYPE ERM_PERIOD_TYPE { get; set; }
        public virtual ERM_SHOCK_GROUP ERM_SHOCK_GROUP { get; set; }
    }
}
