//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERMService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERM_RUN
    {
        public int ERM_RUN_ID { get; set; }
        public int ERM_RUN_VERSION_ID { get; set; }
        public string ERM_RUN_DESC { get; set; }
        public System.DateTime VALUATION_DT { get; set; }
        public System.DateTime CREATE_DT { get; set; }
        public int ERM_BUSINESS_COMPANY_ASSOC_SEQ_ID { get; set; }
        public string INFORCE_FLAG { get; set; }
        public System.DateTime INSERT_DT { get; set; }
    }
}
