//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERMService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERM_FINANCIAL_COLUMN
    {
        public ERM_FINANCIAL_COLUMN()
        {
            this.ERM_FINANCIAL_VALUE = new HashSet<ERM_FINANCIAL_VALUE>();
        }
    
        public int ERM_FINANCIAL_COLUMN_SEQ_ID { get; set; }
        public string ERM_FINANCIAL_COLUMN_NM { get; set; }
        public string ERM_FINANCIAL_COLUMN_HEADER { get; set; }
        public string ERM_FINANCIAL_BUSINESS_NM { get; set; }
        public string ERM_FINANCIAL_COLUMN_DESC { get; set; }
        public string CASHFLOW_BALANCE_FLAG { get; set; }
        public System.DateTime INSERT_DT { get; set; }
    
        public virtual ICollection<ERM_FINANCIAL_VALUE> ERM_FINANCIAL_VALUE { get; set; }
    }
}
