//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERMService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERM_SHOCK_GROUP
    {
        public ERM_SHOCK_GROUP()
        {
            this.ERM_FINANCIAL_VALUE = new HashSet<ERM_FINANCIAL_VALUE>();
        }
    
        public int ERM_SHOCK_GROUP_SEQ_ID { get; set; }
        public int SHOCK_SEQ_ID { get; set; }
        public string PROJECTION_NM { get; set; }
        public string ITERATION_NM { get; set; }
        public int ERM_SHOCK_COUNT { get; set; }
        public System.DateTime INSERT_DT { get; set; }
    
        public virtual ICollection<ERM_FINANCIAL_VALUE> ERM_FINANCIAL_VALUE { get; set; }
    }
}
