//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERMService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERM_FINANCIAL_COLUMN_GROUP
    {
        public int ERM_FINANCIAL_COLUMN_GROUP_SEQ_ID { get; set; }
        public string ERM_FINANCIAL_COLUMN_GROUP_NM { get; set; }
        public string ERM_FINANCIAL_COLUMN_GROUP_DESC { get; set; }
        public System.DateTime INSERT_DT { get; set; }
    }
}
