//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERMService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERM_REPORT_SEGMENT
    {
        public ERM_REPORT_SEGMENT()
        {
            this.ERM_BUSINESS_COMPANY_ASSOC = new HashSet<ERM_BUSINESS_COMPANY_ASSOC>();
            this.ERM_BUSINESS_COMPANY_ASSOC1 = new HashSet<ERM_BUSINESS_COMPANY_ASSOC>();
        }
    
        public int ERM_REPORT_SEGMENT_ID { get; set; }
        public string ERM_REPORT_SEGMENT_TYPE { get; set; }
        public string ERM_REPORT_SEGMENT_TYPE_DESC { get; set; }
        public string ERM_REPORT_SEGMENT_CODE { get; set; }
        public string ERM_REPORT_SEGMENT_DESC { get; set; }
        public System.DateTime INSERT_DT { get; set; }
    
        public virtual ICollection<ERM_BUSINESS_COMPANY_ASSOC> ERM_BUSINESS_COMPANY_ASSOC { get; set; }
        public virtual ICollection<ERM_BUSINESS_COMPANY_ASSOC> ERM_BUSINESS_COMPANY_ASSOC1 { get; set; }
    }
}
