//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERMService.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERMReportingConnection : DbContext
    {
        public ERMReportingConnection()
            : base("name=ERMReportingConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BUSINESS> BUSINESSes { get; set; }
        public virtual DbSet<COMPANY> COMPANies { get; set; }
        public virtual DbSet<ERM_BUSINESS_COMPANY_ASSOC> ERM_BUSINESS_COMPANY_ASSOC { get; set; }
        public virtual DbSet<ERM_FINANCIAL_COLUMN> ERM_FINANCIAL_COLUMN { get; set; }
        public virtual DbSet<ERM_FINANCIAL_COLUMN_GROUP> ERM_FINANCIAL_COLUMN_GROUP { get; set; }
        public virtual DbSet<ERM_FINANCIAL_COLUMN_GROUP_ASSOC> ERM_FINANCIAL_COLUMN_GROUP_ASSOC { get; set; }
        public virtual DbSet<ERM_PERIOD_TYPE> ERM_PERIOD_TYPE { get; set; }
        public virtual DbSet<ERM_REPORT_SEGMENT> ERM_REPORT_SEGMENT { get; set; }
        public virtual DbSet<ERM_RUN> ERM_RUN { get; set; }
        public virtual DbSet<ERM_SHOCK_GROUP> ERM_SHOCK_GROUP { get; set; }
        public virtual DbSet<SHOCK> SHOCKs { get; set; }
        public virtual DbSet<ERM_FINANCIAL_VALUE> ERM_FINANCIAL_VALUE { get; set; }
    }
}
